# Выкладка на боевой сервер (game.lord-server.ru)

name: Deploy to Production Server
on:
  push:
    tags:
      - 20[0-9][0-9].[0-9][0-9]
      - 20[0-9][0-9].[0-9][0-9].p[0-9]


jobs:

  deploy-to-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Update repo & Restart Minetest
        uses: fifsky/ssh-action@v0.0.4
        with:
          host: ${{ secrets.LORD_PROD_HOST }}
          port: ${{ secrets.LORD_PROD_PORT }}
          user: ${{ secrets.LORD_PROD_USER }}
          key: ${{ secrets.LORD_PROD_KEY }}
          command: |
            cd minetest-master/games/lord
            git checkout master
            git pull
            /etc/init.d/mt_server restart
          args: -tt

  merge-to-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Merge `Master` -> `Dev`
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git checkout master
          git checkout dev
          git merge master
          git push
